apiVersion: apps/v1
kind: Deployment
metadata:
  name: licensing-service
  namespace: dev
spec:
  selector:
    matchLabels:
      app: licensing-service
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: licensing-service
    spec:
      containers:
      - name: licensing-service
        image: ${REPOSITORY_TAG}
      nodeSelector:
        cputype: arm
---
apiVersion: v1
kind: Service
metadata:
  name: learning-k8s-sboot-licensing-service
  namespace: dev

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: licensing-service

  ports:
    - name: http
      port: 8080

  type: ClusterIP
